# Generated by Django 3.2.7 on 2021-09-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=3),
        ),
    ]
