# Generated by Django 3.2 on 2021-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_address',
            field=models.BooleanField(default=False),
        ),
    ]
